/**
 * Copyright 2020 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.kogito

unit ExpenseValidationService

rule "Is Item price Valid"
when
    $item: /item[requestExpiration.after(currentTime) && itemPrice<50000]
then
    $item.setValidPrice(Boolean.TRUE);
end

rule "Is Item price Invalid"
when
   $item: /item[requestExpiration.before(currentTime) && itemPrice >= 50000]
then
   $item.setValidPrice(Boolean.FALSE);
end

query "validation"
  $item : /item
end
